name: Build and Release Android App

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Change wrapper permissions
      run: chmod +x ./gradlew

    - name: Run Tests
      run: ./gradlew test

    - name: Build Project
      run: ./gradlew build

    - name: Build Release AAB
      run: ./gradlew bundleRelease

    - uses: actions/upload-artifact@v4
      with:
        name: Upload APK to GitHub Releases
        path: app/build/outputs/apk/release/app-release.apk